CREATE TABLE `admin_users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`username` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`name` varchar(255) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`resetToken` varchar(64),
	`resetTokenExpiry` timestamp,
	`lastLogin` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `admin_users_id` PRIMARY KEY(`id`),
	CONSTRAINT `admin_users_username_unique` UNIQUE(`username`),
	CONSTRAINT `admin_users_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`action` varchar(100) NOT NULL,
	`entity` varchar(100),
	`entityId` int,
	`userId` int,
	`userName` varchar(255),
	`userRole` varchar(50),
	`ipAddress` varchar(45),
	`userAgent` text,
	`oldData` json,
	`newData` json,
	`metadata` json,
	`severity` varchar(20),
	`status` varchar(20),
	`errorMessage` text,
	`duration` int,
	`sessionId` varchar(100),
	`changes` text,
	`resourceType` varchar(100),
	`resourceId` int,
	`resourceName` varchar(255),
	`actionType` varchar(100),
	`userEmail` varchar(255),
	`success` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `backup_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`cronExpression` varchar(100) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastRun` timestamp,
	`nextRun` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `backup_schedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `benefits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('desconto','vale_gas','frete_gratis','brinde','outro') NOT NULL DEFAULT 'outro',
	`value` decimal(10,2),
	`minOrders` int,
	`minSpent` decimal(10,2),
	`expiresAt` timestamp,
	`usageLimit` int,
	`usedCount` int DEFAULT 0,
	`imageUrl` text,
	`terms` text,
	`discountType` enum('fixo','percentual') DEFAULT 'fixo',
	`discountValue` decimal(10,2) DEFAULT '0',
	`voucherProductId` int,
	`voucherProductName` varchar(255),
	`isActive` boolean NOT NULL DEFAULT true,
	`requiresMinOrder` decimal(10,2) DEFAULT '0',
	`maxUsesPerCustomer` int DEFAULT 1,
	`totalUses` int NOT NULL DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `benefits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `chat_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int,
	`delivererId` int,
	`orderId` int,
	`senderType` varchar(50),
	`senderRole` enum('admin','deliverer','customer'),
	`message` text NOT NULL,
	`messageType` varchar(50),
	`attachmentUrl` text,
	`isRead` boolean DEFAULT false,
	`readAt` timestamp,
	`customerPhone` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chat_messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `coupons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`description` varchar(255),
	`type` enum('percentual','fixo') NOT NULL,
	`value` decimal(10,2) NOT NULL,
	`minOrderValue` decimal(10,2) DEFAULT '0',
	`maxUses` int,
	`usedCount` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`validFrom` timestamp NOT NULL DEFAULT (now()),
	`validUntil` timestamp,
	`maxDiscount` decimal(10,2),
	`expiryDate` timestamp,
	`usageLimit` int,
	`expiryAt` timestamp,
	`expiresAt` timestamp,
	`startDate` timestamp,
	`maxUsesPerCustomer` int,
	`applicableProducts` text,
	`applicableCategories` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `coupons_id` PRIMARY KEY(`id`),
	CONSTRAINT `coupons_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `credit_note_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`creditNoteId` int NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`paymentMethod` enum('dinheiro','pix','debito','credito') NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `credit_note_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `credit_notes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int,
	`customerName` varchar(255) NOT NULL,
	`customerPhone` varchar(20),
	`orderId` int,
	`orderNumber` varchar(20),
	`amount` decimal(10,2) NOT NULL,
	`paidAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`remainingAmount` decimal(10,2),
	`dueDate` timestamp NOT NULL,
	`status` enum('pendente','pago','vencido','parcial') NOT NULL DEFAULT 'pendente',
	`description` text,
	`notifiedAt` timestamp,
	`notes` text,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `credit_notes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customer_benefits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int NOT NULL,
	`benefitId` int NOT NULL,
	`grantedAt` timestamp DEFAULT (now()),
	`expiresAt` timestamp,
	`usedAt` timestamp,
	`status` enum('pendente','ativo','usado','expirado','cancelado') NOT NULL DEFAULT 'ativo',
	`orderId` int,
	`notes` text,
	`grantedBy` varchar(255),
	`customerName` varchar(255),
	`benefitName` varchar(255),
	`benefitType` varchar(50),
	`benefitValue` decimal(10,2),
	`usedOrderId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customer_benefits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`email` varchar(320),
	`address` text,
	`addressNumber` varchar(20),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`notes` text,
	`totalOrders` int NOT NULL DEFAULT 0,
	`totalSpent` decimal(12,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastOrderDate` timestamp,
	`complement` varchar(100),
	`zipCode` varchar(10),
	`state` varchar(2),
	`lat` decimal(10,7),
	`lng` decimal(10,7),
	`isActive` boolean NOT NULL DEFAULT true,
	`source` varchar(50),
	`loyaltyPoints` int DEFAULT 0,
	`isBlocked` boolean DEFAULT false,
	`referralCode` varchar(20),
	CONSTRAINT `customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deliverer_locations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`delivererId` int NOT NULL,
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`lat` decimal(10,7),
	`lng` decimal(10,7),
	`accuracy` decimal(8,2),
	`speed` decimal(6,2),
	`heading` decimal(6,2),
	`altitude` decimal(8,2),
	`orderId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `deliverer_locations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `deliverers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`phone` varchar(20),
	`email` varchar(320) NOT NULL DEFAULT '',
	`username` varchar(100) NOT NULL,
	`passwordHash` varchar(255) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`isOnline` boolean NOT NULL DEFAULT false,
	`lastSeen` timestamp,
	`vehicle` varchar(100),
	`notes` text,
	`lastLogin` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`totalDeliveries` int DEFAULT 0,
	`rating` decimal(3,2),
	`currentOrderId` int,
	CONSTRAINT `deliverers_id` PRIMARY KEY(`id`),
	CONSTRAINT `deliverers_username_unique` UNIQUE(`username`)
);
--> statement-breakpoint
CREATE TABLE `discount_coupons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`description` varchar(255),
	`discountType` varchar(50),
	`discountValue` decimal(10,2),
	`minOrderValue` decimal(10,2),
	`maxUses` int,
	`currentUses` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`expiresAt` timestamp,
	`type` varchar(50),
	`value` decimal(10,2),
	`usedCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `discount_coupons_id` PRIMARY KEY(`id`),
	CONSTRAINT `discount_coupons_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `gas_count` (
	`id` int AUTO_INCREMENT NOT NULL,
	`countDate` varchar(10) NOT NULL,
	`productId` int,
	`productName` varchar(255) NOT NULL,
	`initialQty` int DEFAULT 0,
	`soldQty` int NOT NULL DEFAULT 0,
	`finalQty` int DEFAULT 0,
	`difference` int DEFAULT 0,
	`fullQty` int DEFAULT 0,
	`emptyQty` int DEFAULT 0,
	`returnedQty` int DEFAULT 0,
	`notes` text,
	`createdBy` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gas_count_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gas_replenishment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`date` timestamp,
	`supplierName` varchar(255),
	`invoiceNumber` varchar(100),
	`totalCost` decimal(10,2),
	`receivedBy` varchar(255),
	`receivedAt` timestamp,
	`createdBy` varchar(255),
	`delivererId` int,
	`replenishmentDate` timestamp,
	`distributorName` varchar(255),
	`truckPlate` varchar(20),
	`driverName` varchar(255),
	`status` enum('planejado','em_transito','chegou','processando','concluido','cancelado') NOT NULL DEFAULT 'planejado',
	`totalEmptySent` int DEFAULT 0,
	`totalFullReceived` int DEFAULT 0,
	`notes` text,
	`arrivedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gas_replenishment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gas_replenishment_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`replenishmentId` int NOT NULL,
	`productId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`quantity` int DEFAULT 0,
	`unitCost` decimal(10,2),
	`totalCost` decimal(10,2),
	`emptyQty` int,
	`fullQty` int,
	`emptySent` int DEFAULT 0,
	`fullReceived` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `gas_replenishment_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `gas_vouchers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`customerId` int,
	`customerName` varchar(255),
	`customerPhone` varchar(20),
	`productId` int,
	`productName` varchar(255) NOT NULL DEFAULT 'Botijão P13 (13kg)',
	`quantity` int DEFAULT 1,
	`usedQuantity` int DEFAULT 0,
	`status` enum('ativo','usado','expirado','cancelado') NOT NULL DEFAULT 'ativo',
	`expiresAt` timestamp,
	`usedAt` timestamp,
	`orderId` int,
	`notes` text,
	`createdBy` varchar(255),
	`value` decimal(10,2),
	`usedAmount` decimal(10,2),
	`isActive` boolean DEFAULT true,
	`benefitId` int,
	`issuedAt` timestamp DEFAULT (now()),
	`usedOrderId` int,
	`issuedBy` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gas_vouchers_id` PRIMARY KEY(`id`),
	CONSTRAINT `gas_vouchers_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `inventory_adjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`adjustmentDate` timestamp NOT NULL DEFAULT (now()),
	`type` varchar(100) NOT NULL,
	`productId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`previousQty` int NOT NULL,
	`newQty` int NOT NULL,
	`difference` int NOT NULL,
	`reason` varchar(255),
	`referenceId` int,
	`notes` text,
	`createdBy` varchar(255),
	`details` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `inventory_adjustments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `order_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`productId` int,
	`productName` varchar(255) NOT NULL,
	`unitPrice` decimal(10,2) NOT NULL,
	`quantity` int NOT NULL,
	`totalPrice` decimal(10,2),
	`subtotal` decimal(10,2),
	`discount` decimal(10,2) DEFAULT '0',
	`notes` text,
	CONSTRAINT `order_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderNumber` varchar(20) NOT NULL,
	`customerId` int,
	`customerName` varchar(255),
	`customerPhone` varchar(20),
	`customerWhatsapp` varchar(20),
	`address` text,
	`deliveryAddress` text,
	`neighborhood` varchar(100),
	`status` enum('novo','em_preparo','aguardando_entregador','saiu_entrega','entregue','cancelado') NOT NULL DEFAULT 'novo',
	`paymentMethod` enum('dinheiro','pix','debito','credito','fiado') NOT NULL,
	`paymentStatus` varchar(50),
	`paymentConfirmed` boolean NOT NULL DEFAULT false,
	`paymentConfirmedAt` timestamp,
	`delivererId` int,
	`delivererName` varchar(255),
	`totalAmount` decimal(10,2),
	`discountAmount` decimal(10,2) DEFAULT '0',
	`deliveryFee` decimal(10,2) NOT NULL DEFAULT '0',
	`finalAmount` decimal(10,2),
	`subtotal` decimal(10,2),
	`discount` decimal(10,2) DEFAULT '0',
	`total` decimal(10,2),
	`couponCode` varchar(50),
	`couponDiscount` decimal(10,2),
	`change` decimal(10,2),
	`notes` text,
	`source` varchar(50),
	`cancelReason` text,
	`estimatedDelivery` timestamp,
	`deliverBy` timestamp,
	`deliveredAt` timestamp,
	`cancelledAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orders_id` PRIMARY KEY(`id`),
	CONSTRAINT `orders_orderNumber_unique` UNIQUE(`orderNumber`)
);
--> statement-breakpoint
CREATE TABLE `payment_discounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`paymentMethod` enum('dinheiro','pix','debito','credito','fiado') NOT NULL,
	`originalAmount` decimal(10,2),
	`discountAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`finalAmount` decimal(10,2),
	`discountPercentage` decimal(5,2),
	`appliedAt` timestamp,
	`appliedBy` varchar(255),
	`discountType` varchar(50),
	`discountValue` decimal(10,2),
	`isActive` boolean DEFAULT true,
	`discountReason` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_discounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`price` decimal(10,2) NOT NULL,
	`costPrice` decimal(10,2),
	`imageUrl` text,
	`category` varchar(50) NOT NULL DEFAULT 'gas',
	`unit` varchar(20) NOT NULL DEFAULT 'unidade',
	`stockQty` int NOT NULL DEFAULT 0,
	`fullStockQty` int NOT NULL DEFAULT 0,
	`emptyStockQty` int NOT NULL DEFAULT 0,
	`minStock` int NOT NULL DEFAULT 5,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`weight` decimal(8,3),
	`barcode` varchar(50),
	`supplier` varchar(255),
	`notes` text,
	CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promotions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` varchar(50),
	`value` decimal(10,2),
	`minOrderValue` decimal(10,2) DEFAULT '0',
	`maxDiscount` decimal(10,2),
	`productIds` text,
	`categoryIds` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`startDate` timestamp,
	`endDate` timestamp,
	`usageLimit` int,
	`usedCount` int DEFAULT 0,
	`imageUrl` text,
	`terms` text,
	`priority` int DEFAULT 0,
	`buyQuantity` int,
	`getQuantity` int,
	`discountType` enum('percentual','fixo','frete_gratis'),
	`discountValue` decimal(10,2) DEFAULT '0',
	`appliesTo` enum('todos','categoria','produto') DEFAULT 'todos',
	`appliesToCategory` varchar(50),
	`appliesToProductId` int,
	`minQuantity` int DEFAULT 1,
	`validFrom` timestamp,
	`validUntil` timestamp,
	`maxUses` int,
	`maxUsesPerCustomer` int,
	`isFeatured` boolean DEFAULT false,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `promotions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `push_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`endpoint` text NOT NULL,
	`p256dh` text,
	`auth` text,
	`userId` int,
	`userType` varchar(50),
	`delivererId` int,
	`p256dhKey` text,
	`authKey` text,
	`userAgent` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `push_subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`key` varchar(100) NOT NULL,
	`value` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `settings_key_unique` UNIQUE(`key`)
);
--> statement-breakpoint
CREATE TABLE `stock_movements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`type` enum('entrada','saida','ajuste') NOT NULL,
	`quantity` int NOT NULL,
	`previousQty` int NOT NULL,
	`newQty` int NOT NULL,
	`reason` varchar(255),
	`referenceId` int,
	`orderId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stock_movements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `truck_deliveries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deliveryDate` timestamp NOT NULL DEFAULT (now()),
	`licensePlate` varchar(20),
	`driverName` varchar(255),
	`status` enum('planejado','em_transito','chegou','processando','concluido','cancelado') NOT NULL DEFAULT 'planejado',
	`emptyBottlesReceived` int DEFAULT 0,
	`fullBottlesDelivered` int DEFAULT 0,
	`truckPlate` varchar(20),
	`driverId` int,
	`totalEmptyReceived` int,
	`totalFullDelivered` int,
	`arrivedAt` timestamp,
	`notes` text,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `truck_deliveries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `truck_delivery_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`deliveryId` int,
	`truckDeliveryId` int,
	`productId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`quantity` int DEFAULT 0,
	`quantityDelivered` int,
	`quantityReturned` int,
	`unitCost` decimal(10,2),
	`emptyReceived` int,
	`fullDelivered` int,
	`createdAt` timestamp,
	`notes` text,
	CONSTRAINT `truck_delivery_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider` varchar(50),
	`apiUrl` text,
	`apiKey` text,
	`instanceName` varchar(100),
	`phoneNumber` varchar(30) NOT NULL DEFAULT '',
	`isActive` boolean NOT NULL DEFAULT false,
	`webhookUrl` text,
	`webhookSecret` varchar(255),
	`autoReply` boolean DEFAULT false,
	`autoReplyMessage` text,
	`orderConfirmationTemplate` text,
	`orderDeliveredTemplate` text,
	`orderCancelledTemplate` text,
	`newOrderNotification` boolean DEFAULT true,
	`adminPhone` varchar(30),
	`connectionStatus` varchar(50),
	`phoneNumberId` varchar(100),
	`accessToken` text,
	`businessAccountId` varchar(100),
	`notifyOnNewOrder` boolean DEFAULT true,
	`notifyOnConfirmed` boolean DEFAULT true,
	`notifyOnOutForDelivery` boolean DEFAULT true,
	`notifyOnDelivered` boolean DEFAULT true,
	`notifyOnCancelled` boolean DEFAULT true,
	`notifyOnCreditDue` boolean DEFAULT true,
	`templateNewOrder` text,
	`templateConfirmed` text,
	`templateOutForDelivery` text,
	`templateDelivered` text,
	`templateCancelled` text,
	`templateCreditDue` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `whatsapp_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `whatsapp_message_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`phone` varchar(30),
	`message` text,
	`type` varchar(50),
	`status` enum('sent','failed','pending') NOT NULL DEFAULT 'pending',
	`orderId` int,
	`customerId` int,
	`errorMessage` text,
	`updatedAt` timestamp DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`messageId` varchar(100),
	`error` text,
	`whatsappMessageId` varchar(100),
	`sentAt` timestamp,
	`toPhone` varchar(30),
	`toName` varchar(255),
	`messageBody` text,
	`eventType` varchar(50),
	`referenceId` int,
	`referenceType` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `whatsapp_message_log_id` PRIMARY KEY(`id`)
);
